export const GET_ORDER = 'GET_ORDER'
export const GET_USER_ORDER = 'GET_USER_ORDER'
export const CLEAR_ORDER = 'CLEAR_ORDER'
export const ORDER_ERROR = 'ORDER_ERROR'
export const STOP_ORDER = 'STOP_ORDER'
